name: excuse_me
description: Excuse Me mobile client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.0
  firebase_core: ^3.10.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
